export const CHUNK_PROCESSING_CONFIG = {
  chunk_processing: {
    ignore_headers_and_footers: false,
    target_length: 512,
    tokenizer: {
      Enum: 'Cl100kBase',
    },
  },
  expires_in: null,
  high_resolution: false,
  ocr_strategy: 'All',
  segment_processing: {
    Title: {
      crop_image: 'Auto',
      html: 'Auto',
      llm: null,
      markdown: 'Auto',
      embed_sources: ['Markdown'],
      extended_context: false,
    },
    SectionHeader: {
      crop_image: 'Auto',
      html: 'Auto',
      llm: null,
      markdown: 'Auto',
      embed_sources: ['Markdown'],
      extended_context: false,
    },
    Text: {
      crop_image: 'Auto',
      html: 'Auto',
      llm: null,
      markdown: 'Auto',
      embed_sources: ['Markdown'],
      extended_context: false,
    },
    ListItem: {
      crop_image: 'Auto',
      html: 'Auto',
      llm: null,
      markdown: 'Auto',
      embed_sources: ['Markdown'],
      extended_context: false,
    },
    Table: {
      crop_image: 'Auto',
      html: 'LLM',
      llm: 'Summarize the key trends in this table including any context from legends or surrounding text',
      markdown: 'LLM',
      embed_sources: ['LLM', 'Markdown'],
      extended_context: true,
    },
    Picture: {
      crop_image: 'All',
      html: 'LLM',
      llm: 'Summarize the understanding of this image with the context of the surrounding text',
      markdown: 'LLM',
      embed_sources: ['LLM', 'Markdown'],
      extended_context: true,
    },
    Caption: {
      crop_image: 'Auto',
      html: 'Auto',
      llm: null,
      markdown: 'Auto',
      embed_sources: ['Markdown'],
      extended_context: false,
    },
    Formula: {
      crop_image: 'Auto',
      html: 'LLM',
      llm: null,
      markdown: 'LLM',
      embed_sources: ['Markdown'],
      extended_context: true,
    },
    Footnote: {
      crop_image: 'Auto',
      html: 'Auto',
      llm: null,
      markdown: 'Auto',
      embed_sources: ['Markdown'],
      extended_context: false,
    },
    PageHeader: {
      crop_image: 'Auto',
      html: 'Auto',
      llm: null,
      markdown: 'Auto',
      embed_sources: ['Markdown'],
      extended_context: false,
    },
    PageFooter: {
      crop_image: 'Auto',
      html: 'Auto',
      llm: null,
      markdown: 'Auto',
      embed_sources: ['Markdown'],
      extended_context: false,
    },
    Page: {
      crop_image: 'Auto',
      html: 'LLM',
      llm: null,
      markdown: 'LLM',
      embed_sources: ['Markdown'],
      extended_context: true,
    },
  },
  segmentation_strategy: 'LayoutAnalysis',
  pipeline: 'Azure',
  error_handling: 'Fail',
  llm_processing: {
    model_id: 'gemini-pro-1.5',
    fallback_strategy: {
      Model: 'gemini-flash-2.0',
    },
    max_completion_tokens: null,
    temperature: 0,
  },
} as const

export const getMeConfig = (fileUrl: string) => ({
  ...CHUNK_PROCESSING_CONFIG,
  file: fileUrl,
})
